### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by cranst0n** [boeledi/RangeSlider#4]
Version 1.0.0 keeps throwing the following error:

```
I/flutter (19979): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19979): The following NoSuchMethodError was thrown while dispatching a pointer event:
I/flutter (19979): The method 'toDouble' was called on null.
I/flutter (19979): Receiver: null
I/flutter (19979): Tried calling: toDouble()
I/flutter (19979):
I/flutter (19979): When the exception was thrown, this was the stack:
I/flutter (19979): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
I/flutter (19979): #1      double.* (dart:core/runtime/libdouble.dart:26:23)
I/flutter (19979): #2      _RenderRangeSlider._validateActiveThumb (package:flutter_range_slider/src/flutter_range_slider.dart:1118:30)
I/flutter (19979): #3      _RenderRangeSlider.handleEvent (package:flutter_range_slider/src/flutter_range_slider.dart:1093:7)
I/flutter (19979): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (19979): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (19979): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (19979): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (19979): #8      _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (19979): #9      _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (19979):
I/flutter (19979): Event:
I/flutter (19979):   PointerDownEvent(Offset(323.3, 334.7))
I/flutter (19979): Target:
I/flutter (19979):   _RenderRangeSlider#d76fd
I/flutter (19979): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I'm not a flutter expert but it seems like `touchRadiusExpansionRatio` paramter isn't passed down the chain from RangeSlider -> _RangeSliderRenderObjectWidget -> ...

**Comment by boeledi** [comment]
bug has been fixed.  Thanks for spotting this.
